### ISSUE TITLE
Requesting good first issues to contribute

### ISSUE THREAD

**Issue by RahulDubey391** [vvatanabe/dynamomq#1]
Hi @vvatanabe , 

I hope you are doing well. I found this project fascinating and would like to contribute towards bug fixes, enhancements. 

Can you guide me towards working on potential issues so I can start contributing? 

Thanks! ☺

**Comment by vvatanabe** [comment]
@RahulDubey391 
I'm delighted to know that you're interested in contributing to the DynamoMQ project. We are planning to officially release the project next month. Once it's released, we will prepare documentation for those who wish to contribute. Please refer to it for guidance on how to get involved. Thanks!

**Comment by RahulDubey391** [comment]
Thanks @vvatanabe , meanwhile I'll have a look into repo and will raise PR for any potential bug fixes or enhancements!

**Comment by RahulDubey391** [comment]
I'll consider closing this since the contributing documents will be provided!
